name: Continuous Integration
"on":
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
# Allows workflow to run manually

  workflow_dispatch:
  
  
# A workflow run is made up of one or more jobs run sequentailly or in parallel 
jobs:
  build:
    runs-on: ubuntu-latest
# steps represnt a sequence of tasks executed as part of the job
    steps:
    #checkout your repository under $GITHUB_WORKSPACE, so your job can access it
    - name : Checkout
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
        
#    # Git version install
   
#     - name: Install GitVersion
#       uses: ./gitversion/setup
#       with:
#         versionSpec: '5.5.0'
      


   # Calculate the version for the build and display the value of the GITVERSION_NUMBER environment varaible
  
    - name: Semantic Versioning
      id: versioning
      uses: PaulHatch/semantic-version@v4.0.2
      with:
        branch: main
        tag_prefix: "v"
        major_pattern: "BREAKING CHANGE:"
        minor_pattern: "feat:"
        format: "v${major}.${minor}.${patch}-prerelease${increment}"
        
#     - name: Display SemVer
#       run: |
#        echo "SemVer: $GITVERSION_SEMVER"
      
    - name: Create Release
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/create-release@v1
      env:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          prerelease: true   
      
      
     

